version: '3.8'

services:
  db:
    image: percona:8.0
    container_name: percona-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Change the password
      MYSQL_DATABASE: ComputingU
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: